---
# Set the version of Node.js to install ("6.x", "8.x", "10.x", "11.x", etc.).
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "12.x"

# The directory for global installations.
npm_config_prefix: '/home/{{ ansible_user }}/.npm-global'
