---
- name: Add NetBird GPG key to keyring
  become: true
  shell: |
    curl -sSL https://pkgs.netbird.io/debian/public.key | sudo gpg --dearmor --output /usr/share/keyrings/netbird-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/netbird-archive-keyring.gpg

- name: Add NetBird APT repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/netbird-archive-keyring.gpg] https://pkgs.netbird.io/debian stable main"
    filename: netbird
    state: present
    update_cache: false
  notify: Update apt cache

- meta: flush_handlers

- name: Install NetBird
  become: true
  apt:
    name: [netbird, netbird-ui]
    state: present
